FORMAT: 1A
HOST: http://polls.apiblueprint.org/

# HelloRestify API

Hello is a simple API allow posting message from client via REST.

## Message Collection [/hello]

### List All message object [GET]

+ Response 200 (application/json)

        [
        {
        "_id": "5bf54943b5253c154479afc0",
        "message": "HelloWorld Message",
        "updatedAt": "2018-11-21T12:02:11.808Z",
        "createdAt": "2018-11-21T12:02:11.808Z",
        "__v": 0
        },
        {
        "_id": "5bf5494db5253c154479afc1",
        "message": "HelloWorld Message",
        "updatedAt": "2018-11-21T12:02:21.445Z",
        "createdAt": "2018-11-21T12:02:21.445Z",
        "__v": 0
        }     
        ]

### Create a New Message [POST]

Create message via POST method ( No authentication ). accept only ```application/json``` 

+ Request (application/json)

        {
            "message" : "Hello World"
        }

+ Response 200 (application/json)

    + Headers
    
            Server: Hello API
            Content-Length: 22
            Access-Control-Allow-Origin: *
            Access-Control-Allow-Headers: Accept, Accept-Version, Content-Length, Content-MD5, Content-Type, Date, Api-Version, Response-Time
            Access-Control-Expose-Headers: Api-Version, Request-Id, Response-Time
            Connection: Keep-Alive
            Content-MD5: oYHnyT87MYDFXCtd5ucYnw==
            Date: Tue, 27 Nov 2018 09:06:42 GMT
            Request-Id: 2990e1ed-1e9d-4cf2-a11f-0c2c179e5794
            Response-Time: NaN
            
    + Body

            {
                "message": "Got it",
            }